### ISSUE TITLE
Meet lfs quota error

### ISSUE THREAD

**Issue by afalf** [gowitheflow-1998/RAR-b#1]
Thansk for your great work! When I tried to clone this repo, I meet the following errors: batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.   It seems that  your account have not enough  quota  for the lfs files. Do you have plan to release your dataset on hugggingface dataset or else?

**Comment by gowitheflow-1998** [comment]
@afalf thanks for following the work. I will release all datasets to huggingface and update the repo soon.

**Comment by gowitheflow-1998** [comment]
@afalf thanks for reminding about the lfs quota again! I have now removed the datasets from the repo and hosted all the datasets on huggingface at https://huggingface.co/RAR-b. Should be able to git clone now.

Then in the root folder, run the following to set up the datasets:
 
```python
import os
import subprocess

for dataset_name in ["alphanli", "piqa", "siqa", "hellaswag", "quail", "ARC-Challenge", "winogrande", "spartqa", 
"math-pooled", "humanevalpack-mbpp-pooled", "TempReason-l1", "TempReason-l2-pure", "TempReason-l2-fact", 
"TempReason-l2-context", "TempReason-l3-pure", "TempReason-l3-fact", "TempReason-l3-context"]:

    repo_url = f"https://huggingface.co/datasets/RAR-b/{dataset_name}"
    local_path = f"full/{dataset_name}"

    if not os.path.exists(local_path):
        subprocess.run(["git","clone", repo_url, local_path], check=True)
    else:
        print("dataset exists locally")
```

Please let me know if it works. Thanks!
