### ISSUE TITLE
Could you release code for evaluating mrc?

### ISSUE THREAD

**Issue by UnableToUseGit** [gowitheflow-1998/RAR-b#3]

**Comment by gowitheflow-1998** [comment]
@UnableToUseGit thanks for following the repo! I am finding time to wrap the mcr utils and scripts. Looking to push them in 3 days.

**Comment by gowitheflow-1998** [comment]
@UnableToUseGit Sorry that it took a bit longer - Just a quick update that I've pushed the utils and scripts for mcr. It can be run with `python scripts/mcr-eval/evaluate-mcr.py` under the root folder with specifying model names and datasets you want to evaluate in the `evaluate-mcr.py` script. Currently the mcr utils are a bit clunky and in the long term I plan to wrap these classes in a more unified way just like the full setting utils.
