### ISSUE TITLE
Integrate with MTEB?

### ISSUE THREAD

**Issue by Muennighoff** [gowitheflow-1998/RAR-b#4]
Amazing work! It'd be great to have the benchmark integrated in MTEB (https://github.com/embeddings-benchmark/mteb) if you're interested :) I think it'd be great for the community & visibility of your project 😊 We can also add a leaderboard tab if you want to.

**Comment by gowitheflow-1998** [comment]
@Muennighoff Hi Niklas. It'll be a pleasure to integrate RAR-b in MTEB. Thanks for all your amazing work on text embeddings as well! Will reach you in email to chat further?

**Comment by Muennighoff** [comment]
Great! You would need to open a PR like one of these: [LongEmbed](https://github.com/embeddings-benchmark/mteb/pull/393) ; [Law](https://github.com/embeddings-benchmark/mteb/pull/311) ; [FollowIR](https://github.com/embeddings-benchmark/mteb/pull/408) ; [French](https://github.com/embeddings-benchmark/mteb/pull/218) ; [Scandinavian](https://github.com/embeddings-benchmark/mteb/pull/124). 🙌 We're happy to help along the way once the PR is open 😊

**Comment by gowitheflow-1998** [comment]
@Muennighoff Appreciate it. Aiming to start working on this later next week.
